version: '3.8'

services:
  db:
    image: postgres:16
    container_name: rulemate_db
    environment:
      POSTGRES_DB: rulemate
      POSTGRES_USER: rulemate
      POSTGRES_PASSWORD: rulemate1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    container_name: rulemate_neo4j
    environment:
      NEO4J_AUTH: neo4j/rulemate1234
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - ./docs/nodes.csv:/var/lib/neo4j/import/nodes.csv
      - ./docs/edges.csv:/var/lib/neo4j/import/edges.csv

  backend:
    build: .
    container_name: rulemate_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
      - neo4j

volumes:
  postgres_data:
  neo4j_data:
