# Generated by Django 6.0.6 on 2026-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('WITNESS', '목격담'), ('CREATION', '창작담')], default='WITNESS', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('region', models.CharField(default='지역 미상', max_length=100)),
                ('body', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
