# Generated by Django 6.0.6 on 2026-06-05 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=100)),
                ('place', models.TextField(blank=True)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('taboo_text', models.TextField(blank=True)),
                ('event_time', models.CharField(blank=True, max_length=100)),
                ('condition', models.TextField(blank=True)),
                ('ending', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved')], default='draft', max_length=30)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=30)),
                ('prompt_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generated_stories',
            },
        ),
    ]
