# Generated by Django 6.0.6 on 2026-06-05 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generator', '0001_initial'),
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horror_id', models.CharField(max_length=100)),
                ('horror_title', models.CharField(max_length=255)),
                ('horror_type', models.CharField(default='Story', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'horror_id')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedStoryBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='generator.generatedstory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_story_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generated_story_bookmarks',
                'constraints': [models.UniqueConstraint(fields=('user', 'generated_story'), name='uq_generated_story_bookmarks_user_story')],
            },
        ),
        migrations.CreateModel(
            name='PostBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_bookmarks',
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='uq_post_bookmarks_user_post')],
            },
        ),
    ]
