# Generated by Django 6.0.6 on 2026-06-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorrorStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('source_ref_id', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('language', models.CharField(default='ko', max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('url', models.TextField(blank=True)),
                ('preview', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'horror_stories',
                'constraints': [models.UniqueConstraint(fields=('source', 'source_ref_id'), name='uq_horror_stories_source_ref')],
            },
        ),
        migrations.CreateModel(
            name='MythEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='ultimate_global_mythology_1000', max_length=100)),
                ('source_ref_id', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('behavior', models.TextField(blank=True)),
                ('weakness', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('signs', models.TextField(blank=True)),
                ('survival_rules', models.JSONField(blank=True, default=list)),
                ('source_site', models.CharField(blank=True, max_length=100)),
                ('source_url', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'myth_entities',
                'constraints': [models.UniqueConstraint(fields=('source', 'source_ref_id'), name='uq_myth_entities_source_ref')],
            },
        ),
        migrations.CreateModel(
            name='Superstition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='misin', max_length=100)),
                ('source_ref_id', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'superstitions',
                'constraints': [models.UniqueConstraint(fields=('source', 'source_ref_id'), name='uq_superstitions_source_ref')],
            },
        ),
    ]
