# Generated by Django 6.0.6 on 2026-06-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcinsidePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='dcinside_gongpow', max_length=100)),
                ('source_ref_id', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('WITNESS', '목격담'), ('CREATION', '창작담')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('region', models.CharField(default='한국', max_length=100)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dcinside_posts',
                'constraints': [models.UniqueConstraint(fields=('source', 'source_ref_id'), name='uq_dcinside_posts_source_ref')],
            },
        ),
    ]
